import { Banknote, CalendarClock, CircleDollarSign, HandCoins, Plus } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { Modal } from '../../components/ui/Modal'
import { listarDeudas, obtenerResumenComercial, registrarDeuda, registrarMovimiento, registrarPagoDeuda } from '../../services/comercial.service'
import { listarPedidos } from '../../services/pedidos.service'
import type { Deuda, Pedido, ResumenComercial } from '../../types/domain'

const today = () => new Date().toISOString().slice(0, 10)
export function DeudasPage() {
  const [items, setItems] = useState<Deuda[]>([]), [debtOpen, setDebtOpen] = useState(false), [paying, setPaying] = useState<Deuda | null>(null), [salaryOpen, setSalaryOpen] = useState(false)
  const [summary, setSummary] = useState<ResumenComercial>({ ventas: 0, cobrado: 0, por_cobrar: 0, gastos: 0, costos_productos: 0, saldo_cuenta: 0, pedidos: 0 })
  const [orders, setOrders] = useState<Pedido[]>([])
  useEffect(() => { void Promise.all([listarDeudas(), obtenerResumenComercial(), listarPedidos()]).then(([debts, commercial, allOrders]) => { setItems(debts); setSummary(commercial); setOrders(allOrders) }).catch(() => toast.error('No se pudieron cargar las deudas. Ejecuta primero la migración de Supabase.')) }, [])
  const totals = useMemo(() => items.filter((item) => item.estado !== 'cancelada').reduce((r, item) => { r.total += Number(item.monto_total); r.paid += Number(item.monto_pagado); r.pending += Math.max(0, Number(item.monto_total) - Number(item.monto_pagado)); if (item.fecha_vencimiento && item.fecha_vencimiento < today() && item.estado === 'pendiente') r.overdue++ ; return r }, { total: 0, paid: 0, pending: 0, overdue: 0 }), [items])
  const plan = useMemo(() => {
    const limit = new Date(); limit.setDate(limit.getDate() + 7); const nextWeek = limit.toISOString().slice(0, 10)
    const priorities = items.filter((item) => item.estado === 'pendiente').sort((a, b) => (a.fecha_vencimiento || '9999').localeCompare(b.fecha_vencimiento || '9999'))
    const urgent = priorities.filter((item) => item.fecha_vencimiento && item.fecha_vencimiento <= nextWeek).reduce((sum, item) => sum + Math.max(0, Number(item.monto_total) - Number(item.monto_pagado)), 0)
    const delivered = orders.filter((order) => order.estado === 'entregado')
    const deliveredSales = delivered.reduce((sum, order) => sum + Number(order.total), 0)
    const deliveredCosts = delivered.reduce((sum, order) => sum + (order.gastos ?? []).reduce((cost, expense) => cost + Number(expense.monto), 0), 0)
    const realizedProfit = Math.max(0, deliveredSales - deliveredCosts)
    const balance = Number(summary.saldo_cuenta)
    const usableProfit = Math.max(0, Math.min(realizedProfit, balance))
    const debtPayment = Math.min(usableProfit, totals.pending)
    const afterDebts = Math.max(0, usableProfit - debtPayment)
    return { priorities, urgent, balance, deliveredSales, deliveredCosts, realizedProfit, debtPayment, reserve: afterDebts * .2, stock: afterDebts * .5, salary: afterDebts * .3 }
  }, [items, orders, summary.saldo_cuenta, totals.pending])
  return <div><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">Compromisos del negocio</p><h1 className="page-title">Deudas y salario</h1><p className="page-subtitle">Controla lo que debes y registra tu pago personal sin mezclarlo con proveedores.</p></div><div className="flex flex-wrap gap-2"><button className="subtle-button px-4" onClick={() => setSalaryOpen(true)}><Banknote size={17} /> Registrar mi salario</button><button className="primary-button px-5" onClick={() => setDebtOpen(true)}><Plus size={17} /> Nueva deuda</button></div></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CircleDollarSign} label="Deuda total" value={totals.total} /><Metric icon={HandCoins} label="Total abonado" value={totals.paid} /><Metric icon={CalendarClock} label="Saldo pendiente" value={totals.pending} accent /><Metric icon={CalendarClock} label="Deudas vencidas" value={totals.overdue} count /></div>
    <section className="form-section mt-6"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="flex items-center gap-2 font-semibold"><CircleDollarSign size={18} className="text-accent" /> Distribución de la ganancia entregada</h2><p className="mt-1 text-xs text-muted">Solo se consideran pedidos marcados como Entregado. Ningún pago se realiza sin tu confirmación.</p></div><span className="status-badge status-neutral">Saldo de cuenta: USD {plan.balance.toFixed(2)}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Budget label="Ventas ya entregadas" value={plan.deliveredSales} detail="Pedidos finalizados" /><Budget label="Costos de esas ventas" value={plan.deliveredCosts} detail="Proveedor, envío, delivery y gastos" warn /><Budget label="Ganancia realizada" value={plan.realizedProfit} detail="Base disponible para distribuir" accent /></div><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Budget label="1. Pagar deudas" value={plan.debtPayment} detail="Primera prioridad" warn /><Budget label="2. Reserva" value={plan.reserve} detail="20% de lo restante" /><Budget label="3. Reinvertir en stock" value={plan.stock} detail="50% de lo restante" /><Budget label="4. Tu salario" value={plan.salary} detail="30% de lo restante" accent /></div>{plan.priorities.length > 0 && <div className="mt-5 rounded-xl border border-line bg-black/10 p-4"><strong className="text-xs uppercase tracking-wider text-muted">Orden recomendado para pagar deudas con la ganancia</strong><div className="mt-3 space-y-2">{plan.priorities.slice(0, 3).map((item, index) => <div className="flex items-center justify-between gap-3 text-sm" key={item.id}><span><b className="mr-2 text-accent">{index + 1}.</b>{item.acreedor} · {item.concepto}</span><strong>USD {Math.max(0, Number(item.monto_total) - Number(item.monto_pagado)).toFixed(2)}</strong></div>)}</div></div>}</section>
    <div className="mt-6 overflow-hidden rounded-2xl border border-line bg-panel">{items.map((item) => { const pending = Math.max(0, Number(item.monto_total) - Number(item.monto_pagado)); const overdue = Boolean(item.fecha_vencimiento && item.fecha_vencimiento < today() && item.estado === 'pendiente'); return <article key={item.id} className="grid gap-4 border-b border-line p-5 last:border-0 lg:grid-cols-[1.4fr_.7fr_.7fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><strong>{item.acreedor}</strong><span className={`status-badge ${item.estado === 'pagada' ? 'status-success' : overdue ? 'status-danger' : 'status-neutral'}`}>{item.estado === 'pagada' ? 'Pagada' : overdue ? 'Vencida' : 'Pendiente'}</span></div><p className="mt-1 text-xs text-muted">{item.concepto}{item.fecha_vencimiento ? ` · Vence ${formatDate(item.fecha_vencimiento)}` : ''}</p></div><Amount label="Total" value={item.monto_total} /><Amount label="Pendiente" value={pending} accent /><button className="primary-button px-4" disabled={!pending || item.estado !== 'pendiente'} onClick={() => setPaying(item)}>Registrar abono</button></article>})}{!items.length && <div className="p-10 text-center text-sm text-muted">No hay deudas registradas.</div>}</div>
    <DebtModal open={debtOpen} onClose={() => setDebtOpen(false)} onSaved={(item) => { setItems((all) => [item, ...all]); setDebtOpen(false) }} />
    <PaymentModal debt={paying} onClose={() => setPaying(null)} onSaved={(item) => { setItems((all) => all.map((current) => current.id === item.id ? item : current)); setPaying(null) }} />
    <SalaryModal open={salaryOpen} onClose={() => setSalaryOpen(false)} />
  </div>
}

function DebtModal({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: (item: Deuda) => void }) { const [form, setForm] = useState({ acreedor: '', concepto: '', monto_total: 0, fecha_deuda: today(), fecha_vencimiento: '', notas: '' }), [saving, setSaving] = useState(false); const submit = async (e: FormEvent) => { e.preventDefault(); if (!form.acreedor.trim() || !form.concepto.trim() || form.monto_total <= 0) return toast.error('Completa acreedor, concepto y monto.'); setSaving(true); try { const saved = await registrarDeuda({ ...form, fecha_vencimiento: form.fecha_vencimiento || null, notas: form.notas || null }); onSaved(saved); toast.success('Deuda registrada.') } catch { toast.error('No se pudo registrar la deuda.') } finally { setSaving(false) } }; return <Modal open={open} onClose={onClose} title="Registrar deuda"><form className="form-grid" onSubmit={(e) => void submit(e)}><Field label="Acreedor"><input placeholder="Proveedor o persona" value={form.acreedor} onChange={(e) => setForm({ ...form, acreedor: e.target.value })} /></Field><Field label="Concepto"><input placeholder="Compra, préstamo…" value={form.concepto} onChange={(e) => setForm({ ...form, concepto: e.target.value })} /></Field><Field label="Monto total"><input type="number" min=".01" step=".01" value={form.monto_total} onChange={(e) => setForm({ ...form, monto_total: Number(e.target.value) })} /></Field><Field label="Fecha de la deuda"><input type="date" value={form.fecha_deuda} onChange={(e) => setForm({ ...form, fecha_deuda: e.target.value })} /></Field><Field label="Vencimiento (opcional)"><input type="date" value={form.fecha_vencimiento} onChange={(e) => setForm({ ...form, fecha_vencimiento: e.target.value })} /></Field><Field label="Notas"><input value={form.notas} onChange={(e) => setForm({ ...form, notas: e.target.value })} /></Field><Actions saving={saving} onClose={onClose} label="Guardar deuda" /></form></Modal> }
function PaymentModal({ debt, onClose, onSaved }: { debt: Deuda | null; onClose: () => void; onSaved: (item: Deuda) => void }) { const pending = debt ? Math.max(0, Number(debt.monto_total) - Number(debt.monto_pagado)) : 0; const [amount, setAmount] = useState(0), [profit, setProfit] = useState(0), [date, setDate] = useState(today()), [method, setMethod] = useState('Transferencia'), [notes, setNotes] = useState(''), [saving, setSaving] = useState(false); useEffect(() => { setAmount(pending); setProfit(0); setDate(today()); setNotes('') }, [debt?.id, pending]); const submit = async (e: FormEvent) => { e.preventDefault(); if (!debt || profit > amount) return toast.error('La parte pagada con ganancia no puede superar el abono.'); setSaving(true); try { const updated = await registrarPagoDeuda(debt, amount, date, method, notes, profit); onSaved(updated); toast.success(`Pago registrado: USD ${profit.toFixed(2)} de ganancia y USD ${Math.max(0, amount-profit).toFixed(2)} del negocio.`) } catch (error) { toast.error(error instanceof Error ? error.message : 'No se pudo registrar el abono.') } finally { setSaving(false) } }; return <Modal open={Boolean(debt)} onClose={onClose} title={`Abonar a ${debt?.acreedor || ''}`}><form className="form-grid" onSubmit={(e) => void submit(e)}><div className="col-span-full rounded-xl border border-line p-4 text-sm">Saldo pendiente: <strong className="text-accent">USD {pending.toFixed(2)}</strong></div><Field label="Monto total del abono"><input type="number" min=".01" max={pending} step=".01" value={amount || ''} onChange={(e) => setAmount(Number(e.target.value))} /></Field><Field label="Parte tomada de mi ganancia"><input type="number" min="0" max={amount} step=".01" value={profit || ''} onChange={(e) => setProfit(Number(e.target.value))} /></Field><div className="col-span-full rounded-xl border border-accent/20 bg-accent/[.04] p-4 text-sm">Parte tomada del saldo del negocio: <strong>USD {Math.max(0, amount-profit).toFixed(2)}</strong></div><Field label="Fecha"><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></Field><Field label="Método"><input value={method} onChange={(e) => setMethod(e.target.value)} /></Field><Field label="Notas"><input value={notes} onChange={(e) => setNotes(e.target.value)} /></Field><Actions saving={saving} onClose={onClose} label="Registrar abono" /></form></Modal> }
function SalaryModal({ open, onClose }: { open: boolean; onClose: () => void }) { const [form, setForm] = useState({ fecha: today(), periodo: new Intl.DateTimeFormat('es-NI', { month: 'long', year: 'numeric' }).format(new Date()), monto: 0, metodo: 'Transferencia', notas: '' }), [saving, setSaving] = useState(false); const submit = async (e: FormEvent) => { e.preventDefault(); if (form.monto <= 0) return toast.error('Indica el monto de tu salario.'); setSaving(true); try { await registrarMovimiento({ fecha: `${form.fecha}T12:00:00`, tipo: 'retiro', descripcion: `Salario del propietario · ${form.periodo}`, monto: form.monto, metodo: form.metodo || null, pedido_id: null, observaciones: form.notas || null }); toast.success('Salario registrado y descontado de Mi cuenta.'); onClose() } catch { toast.error('No se pudo registrar el salario.') } finally { setSaving(false) } }; return <Modal open={open} onClose={onClose} title="Registrar mi salario"><form className="form-grid" onSubmit={(e) => void submit(e)}><Field label="Periodo"><input value={form.periodo} onChange={(e) => setForm({ ...form, periodo: e.target.value })} /></Field><Field label="Fecha de pago"><input type="date" value={form.fecha} onChange={(e) => setForm({ ...form, fecha: e.target.value })} /></Field><Field label="Monto"><input type="number" min=".01" step=".01" value={form.monto} onChange={(e) => setForm({ ...form, monto: Number(e.target.value) })} /></Field><Field label="Método"><input value={form.metodo} onChange={(e) => setForm({ ...form, metodo: e.target.value })} /></Field><label className="form-field col-span-full"><span>Observaciones</span><textarea rows={3} value={form.notas} onChange={(e) => setForm({ ...form, notas: e.target.value })} /></label><Actions saving={saving} onClose={onClose} label="Registrar salario" /></form></Modal> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="form-field"><span>{label}</span>{children}</label> }
function Actions({ saving, onClose, label }: { saving: boolean; onClose: () => void; label: string }) { return <div className="col-span-full flex justify-end gap-2"><button type="button" className="subtle-button" onClick={onClose}>Cancelar</button><button className="primary-button px-5" disabled={saving}>{saving ? 'Guardando…' : label}</button></div> }
function Metric({ icon: Icon, label, value, accent, count }: { icon: typeof HandCoins; label: string; value: number; accent?: boolean; count?: boolean }) { return <article className="metric-card"><Icon size={19} className={accent ? 'text-accent' : 'text-muted'} /><p className="mt-5 text-xs text-muted">{label}</p><strong className={`mt-1 block text-2xl ${accent ? 'text-accent' : ''}`}>{count ? value : `USD ${value.toFixed(2)}`}</strong></article> }
function Amount({ label, value, accent }: { label: string; value: number; accent?: boolean }) { return <div><span className="text-[10px] uppercase text-muted">{label}</span><strong className={`mt-1 block ${accent ? 'text-amber-300' : ''}`}>USD {Number(value).toFixed(2)}</strong></div> }
function Budget({ label, value, detail, accent, warn }: { label: string; value: number; detail: string; accent?: boolean; warn?: boolean }) { return <div className="rounded-xl border border-line bg-white/[.02] p-4"><span className="text-xs text-muted">{label}</span><strong className={`mt-2 block text-xl ${accent ? 'text-accent' : warn && value > 0 ? 'text-amber-300' : ''}`}>USD {value.toFixed(2)}</strong><small className="mt-1 block text-muted">{detail}</small></div> }
function formatDate(value: string) { return new Intl.DateTimeFormat('es-NI').format(new Date(`${value}T12:00:00`)) }
