-- Nombres neutros de productos (2026-09-24)
-- La tienda ya muestra nombres neutros (nombresReales en productos.js). Esto pone esos
-- mismos nombres en el tracking: catálogo (productos), productos de pedidos ya hechos
-- (pedido_items → panel y seguimiento del cliente) y encargos web (solicitudes).
-- Solo cambia el texto del nombre; códigos, marca, precios y estados no se tocan.
-- Los nombres anteriores quedan en public.respaldo_nombres_20260924 para poder revertir.
-- No dispara correos: los webhooks de pedido_items solo reaccionan a estado_item /
-- qc_enviado_at, y el de solicitudes solo a pago_reportado_at.

begin;

create temp table nombres_nuevos (codigo text primary key, nombre text not null) on commit drop;
insert into nombres_nuevos (codigo, nombre) values
  ('CL0001', 'Sneaker Low Top Gamuza Negro'),
  ('CL0002', 'Sneaker Low Top Gamuza Azul Marino'),
  ('CL0003', 'Sneaker Low Top Gamuza Azul'),
  ('CL0004', 'Sneaker Low Top Spikes Negro Monograma'),
  ('CL0005', 'Sneaker Low Top Spikes Gamuza Gris'),
  ('CL0006', 'Sneaker Low Top Spikes Gamuza Azul Marino'),
  ('CL0007', 'Sneaker Low Top Spikes Gamuza Negro'),
  ('CL0008', 'Sneaker High Top Paisley Negro'),
  ('CL0009', 'Sneaker Low Top Cristales Gris Plomo'),
  ('CL0010', 'Sneaker Low Top Blanco Ribete Rojo'),
  ('CL0011', 'Sneaker Low Top Spikes Azul/Negro'),
  ('CL0012', 'Sneaker Low Top Cristales Negro'),
  ('CL0013', 'Sneaker High Top Spikes Negro'),
  ('CL0014', 'Sneaker Low Top Spikes Blanco'),
  ('CL0015', 'Sneaker Low Top Charol Negro/Blanco'),
  ('CL0016', 'Sneaker Low Top Negro Ribete Rojo'),
  ('CL0017', 'Sneaker High Top Gamuza Negro'),
  ('CL0018', 'Sneaker Low Top Spikes Cristales Negro'),
  ('CL0019', 'Sneaker High Top Spikes Plata/Negro'),
  ('CL0020', 'Sneaker Low Top Spikes Camuflaje Negro'),
  ('CL0021', 'Sneaker Low Top Glitter Negro'),
  ('CL0022', 'Sneaker Low Top Gamuza Negro Suela Roja'),
  ('CL0023', 'Sneaker Low Top Cuero Granulado Negro'),
  ('CL0024', 'Sneaker High Top Cuero Negro'),
  ('CL0025', 'Sneaker Low Top Cristales Turquesa'),
  ('CL0026', 'Sneaker Low Top Cuero Blanco Talón Negro'),
  ('CL0027', 'Sneaker Low Top Spikes Tonal Azul Marino'),
  ('CL0028', 'Sneaker Low Top Spikes Estampado Geométrico'),
  ('CL0029', 'Sneaker Low Top Spikes Estampado Multicolor'),
  ('CL0030', 'Sneaker Low Top Cuero Negro/Blanco'),
  ('CL0031', 'Sneaker Low Top Cuero Blanco'),
  ('CL0032', 'Slide Spikes Negro'),
  ('CL0033', 'Slide Cristales Negro'),
  ('CL0034', 'Sneaker Low Top Spikes Glitter Negro/Plata'),
  ('CL0035', 'Chancla Tachuelas Gris'),
  ('CL0036', 'Slide Tachuelas Rojo'),
  ('CL0037', 'Slide Tachuelas Negro/Rojo'),
  ('CL0038', 'Sneaker Low Top Panel Tejido Negro'),
  ('CL0039', 'Sneaker Low Top Panel Tejido Azul/Blanco'),
  ('CL0040', 'Sneaker Low Top Tie-Dye Azul'),
  ('CL0041', 'Mocasín Terciopelo Cristales Negro'),
  ('CL0042', 'Mocasín Spikes Gamuza Negro'),
  ('CL0043', 'Sneaker Low Top Rayas Azul Marino'),
  ('CL0044', 'Sneaker Low Top Malla Negro Total'),
  ('CL0045', 'Sneaker High Top Jacquard Negro'),
  ('CL0046', 'Sneaker Low Top Estrellas Cristales Negro'),
  ('CL0047', 'Sneaker Low Top Tachas Gamuza Negro'),
  ('CL0048', 'Sneaker Low Top Spikes Glitter Plata'),
  ('CL0049', 'Sneaker Low Top Cristales Blanco/Plata'),
  ('CL0050', 'Sneaker Low Top Spikes Glitter Gris Oscuro'),
  ('CL0051', 'Sneaker High Top Spikes Negro/Blanco'),
  ('CL0052', 'Sneaker High Top Spikes Blanco/Negro'),
  ('CL05053', 'Sneaker High Top Cristales Negro/Rojo'),
  ('CL0054', 'Sneaker High Top Cristales Plata'),
  ('AM001', 'Sneaker Lona Graffiti Negro'),
  ('AM002', 'Sneaker Oversized Cuero Negro'),
  ('AM003', 'Sneaker Oversized Cristales Negro'),
  ('AM004', 'Sneaker Oversized Blanco Talón Rojo'),
  ('AM005', 'Sneaker Oversized Brillantes Negro Total'),
  ('AM006', 'Sneaker Oversized Blanco Talón Negro'),
  ('AM007', 'Sneaker Oversized Cristales Negro/Plata'),
  ('STY001', 'Short Mesh Número 80 Crema'),
  ('STY002', 'Short Mesh Número 80 Negro'),
  ('AR001', 'Sneaker Low Top Lona Estrellas Azul'),
  ('AR002', 'Slide Logo Negro'),
  ('AR003', 'Sneaker Lona Esqueleto Negro'),
  ('AR004', 'Sneaker Low Top Bandana Blanco'),
  ('AR005', 'Sneaker Chunky Blanco/Negro'),
  ('BL001', 'Sneaker Sock Knit Negro Total'),
  ('BL002', 'Sneaker Sock Knit Gris'),
  ('BL003', 'Sneaker Sock Knit Negro/Blanco'),
  ('BL004', 'Sneaker Sock Knit Triple Negro'),
  ('BL005', 'Sneaker Sock Knit Logo Suela Negro'),
  ('BL006', 'Sneaker Chunky Runner Negro'),
  ('BL007', 'Slide Peluche Gris'),
  ('BL008', 'Slide Logo Amarillo Neón'),
  ('BL009', 'Slide Logo Negro/Verde'),
  ('BK001', 'Clog Suede Gris'),
  ('BK002', 'Clog Suede Negro'),
  ('BK003', 'Clog Suede Arena'),
  ('BK004', 'Clog Suede Taupe'),
  ('BK005', 'Sandalia Dos Tiras Suede Taupe'),
  ('BK006', 'Sandalia Dos Tiras Suede Marrón'),
  ('BK007', 'Clog Suede Herrajes Negro'),
  ('BR001', 'Sneaker Lona Cuadros Beige'),
  ('BR002', 'Slide Cuadros Beige'),
  ('CH001', 'Sneaker Low Top Monograma Transparente'),
  ('CH002', 'Bota Alta Jacquard Negro'),
  ('CH003', 'Sneaker Low Top Bordado Negro Total'),
  ('CH004', 'Sneaker High Top Lona Monograma Negro'),
  ('CH005', 'Sneaker High Top Lona Estampada Blanco'),
  ('CH006', 'Sneaker High Top Lona Monograma Blanco/Gris'),
  ('CV001', 'Sneaker Low Top Lona Corazón Blanco'),
  ('D&C001', 'Sneaker Low Top Cuero Blanco/Azul'),
  ('D&C002', 'Sneaker Low Top Cuero Blanco/Negro'),
  ('D&C003', 'Sneaker Low Top Logo Blanco/Verde'),
  ('D&C004', 'Sneaker Low Top Logo Blanco/Rojo'),
  ('D&C005', 'Sneaker Low Top Cuero Negro Total'),
  ('D&C006', 'Sneaker Low Top Cuero Blanco Total'),
  ('D&C007', 'Sneaker Low Top Corona Bordada Negro'),
  ('D&C008', 'Sneaker Low Top Corona Bordada Blanco'),
  ('D&C009', 'Sneaker Slip-On Knit Blanco/Negro'),
  ('D&C011', 'Sneaker Low Top Talón Plata Blanco'),
  ('D&C012', 'Sneaker Low Top Graffiti Blanco/Negro'),
  ('D&C013', 'Sneaker Slip-On Cristales Rojo'),
  ('D&C014', 'Sneaker Slip-On Cristales Negro'),
  ('D&C015', 'Sneaker Low Top Estampado Azul Cobalto'),
  ('D&C016', 'Sneaker Low Top Talón Charol Blanco/Negro'),
  ('D&C017', 'Sneaker Low Top Graffiti Escudo Blanco'),
  ('D&C018', 'Sneaker Low Top Cuero Negro Talón Plata'),
  ('D&C019', 'Sneaker Low Top Escudo Bordado Negro'),
  ('D&C020', 'Sneaker Low Top Nappa Blanco/Negro'),
  ('D&CW001', 'Sneaker Low Top Logo Maxi Blanco/Negro'),
  ('GG001', 'Sneaker Vintage Star Blanco/Gris'),
  ('GG002', 'Sneaker Vintage Star Crema/Azul Marino'),
  ('GG003', 'Sneaker Vintage Star Malla Beige'),
  ('GG004', 'Sneaker Vintage Star Blanco/Marrón'),
  ('GG005', 'Sneaker Vintage Low Top Blanco/Verde'),
  ('GG006', 'Sneaker Vintage Star Blanco/Negro'),
  ('GG007', 'Sneaker Vintage Star Crema/Azul Metalizado'),
  ('GG008', 'Sneaker Vintage Star Blanco/Gris Claro'),
  ('GG009', 'Sneaker Vintage Star Crema/Azul'),
  ('GG010', 'Sneaker Vintage Star Blanco/Rojo'),
  ('GG011', 'Sneaker Vintage Star Blanco/Azul Eléctrico'),
  ('GG012', 'Sneaker Vintage Star Blanco/Gris Oscuro'),
  ('GG013', 'Sneaker Vintage Star Blanco/Gris Talón Verde'),
  ('LP001', 'Mocasín Gamuza Azul Marino'),
  ('LV001', 'Sneaker Skate Malla Negro'),
  ('LV002', 'Sneaker Trainer Cuero Negro'),
  ('MM001', 'Sneaker Low Top Cuero Blanco Suela Gum'),
  ('MM002', 'Sneaker Low Top Gamuza Gris Antracita'),
  ('MM003', 'Sneaker Low Top Gamuza Negro Suela Gum'),
  ('MM004', 'Sneaker Low Top Paint Splatter Negro'),
  ('MM005', 'Sneaker Low Top Paint Splatter Blanco'),
  ('OFW001', 'Sneaker Urban Cuero Negro'),
  ('OFW002', 'Sneaker Vulcanizado Negro/Turquesa'),
  ('OFW003', 'Sneaker Vulcanizado Rayas Negro/Fucsia'),
  ('OFW004', 'Sneaker Urban Blanco/Rojo'),
  ('OFW005', 'Sneaker Vulcanizado Blanco Flecha Roja'),
  ('OFW006', 'Sneaker High Top Retro Blanco'),
  ('ST001', 'Sneaker Court Cuero Blanco/Negro'),
  ('VL001', 'Sneaker Low Top Blanco Banda Azul'),
  ('VL002', 'Sneaker Low Top Blanco Banda Roja'),
  ('VJ001', 'Sneaker Velcro Blanco/Negro'),
  ('VJW001', 'Sneaker Low Top Cuero Blanco/Rosa'),
  ('VJW-M002', 'Sneaker Low Top Cuero Negro Logo Blanco'),
  ('PHM001', 'Sneaker Low Top Vintage Blanco/Negro'),
  ('001W', 'Sneaker Vintage Star Glitter Morado'),
  ('002W', 'Sneaker Vintage Star Blanco Talón Negro'),
  ('003W', 'Sneaker Vintage Star Lona Blanco/Negro'),
  ('004W', 'Sneaker Vintage Star Lettering Blanco/Azul'),
  ('005W', 'Sneaker Vintage Low Top Azul Metalizado'),
  ('006W', 'Sneaker Vintage Star Graffiti Blanco'),
  ('007W', 'Sneaker Vintage Star Glitter Rosa'),
  ('008W', 'Sneaker Vintage Star Leopardo'),
  ('009W', 'Sneaker Vintage Star Glitter Plata'),
  ('010W', 'Sneaker Vintage Velcro Dorado'),
  ('011W', 'Sneaker Low Top Spikes Gamuza Rosa'),
  ('012W', 'Slide Bordado Azul Marino'),
  ('013W', 'Sneaker Plataforma Estrellas Blanco/Rosa'),
  ('014W', 'Mule Denim Rosa'),
  ('015W', 'Stiletto Charol Negro'),
  ('016W', 'Slide Denim Azul'),
  ('017W', 'Slide Bordado Dorado'),
  ('GGW001', 'Sneaker Vintage Star Blanco Tonal'),
  ('GGW002', 'Sneaker Vintage Star Glitter Plata/Gris'),
  ('GGW003', 'Sneaker Vintage Star Blanco Glitter Dorado'),
  ('GGW004', 'Sneaker Vintage Star Cristales Blanco/Plata'),
  ('GGW005', 'Sneaker Vintage Star Blanco/Verde'),
  ('GGW006', 'Sneaker Vintage Star Crema/Rojo'),
  ('GGW007', 'Sneaker Vintage Star Blanco/Azul'),
  ('GGW008', 'Sneaker Vintage Star Glitter Negro/Dorado'),
  ('GGW009', 'Sneaker Vintage Star Glitter Burdeos/Plata'),
  ('BEAR001', 'Figura Bear 400% Monograma Multicolor'),
  ('BEAR002', 'Figura Bear 400% Héroe Rojo/Azul'),
  ('BEAR003', 'Figura Bear 400% Cromado Plata'),
  ('BEAR004', 'Figura Bear 400% Camuflaje'),
  ('BEAR005', 'Figura Bear 400% Arte Clásico'),
  ('BEAR006', 'Figura Bear 400% Dorado'),
  ('BEAR007', 'Figura Bear 400% Galáctico Blanco'),
  ('BEAR008', 'Figura Bear 400% Amarillo'),
  ('KAW001', 'Figura Art Toy Marrón 30 cm'),
  ('KAW002', 'Figura Art Toy Negro 37 cm'),
  ('KAW003', 'Figura Art Toy Reclinada Azul 29 cm'),
  ('KAW004', 'Figura Art Toy Rojo/Gris 37 cm'),
  ('KAW005', 'Figura Art Toy Rosa 30 cm'),
  ('CHROME001', 'Lentes Montura Cruz Premium'),
  ('OFC001', 'Manta Tejida Rayas Blanco/Negro'),
  ('FERRA001', 'Cinturón Cuero Hebilla Dorada'),
  ('LVB001', 'Maleta Carry-On Monograma Marrón'),
  ('LVB002', 'Bolso de Viaje Lunares Rojo/Negro'),
  ('SUPR001', 'Maleta Aluminio Rojo'),
  ('ROW1', 'Reloj Colgante Octagonal Colores'),
  ('ROW2', 'Bolso Messenger Monograma Negro'),
  ('ROW3', 'Tarjetero Lona Chevron Colores'),
  ('ROW4', 'Mochila Neopreno Negro'),
  ('ESB001', 'Mochila Logo Negro'),
  ('CACH001', 'Gorra Trucker Cruces Negro'),
  ('CACH002', 'Gorra Trucker Parche Negro'),
  ('CACH003', 'Gorra Trucker Parche Labios Negro'),
  ('CACH004', 'Gorra Trucker Parche Negro/Rosa'),
  ('CACH005', 'Gorra Trucker Parche Blanco/Negro'),
  ('001R', 'Chaqueta Varsity Parches Gris'),
  ('002R', 'Chaqueta Varsity Negro/Crema'),
  ('003R', 'Chaqueta Varsity Parches Beige'),
  ('004R', 'Suéter Punto Logo Azul/Negro'),
  ('005R', 'Camiseta Estampado Espalda Negro/Blanco'),
  ('006R', 'Camiseta Oversized Estampado Negro/Blanco'),
  ('007R', 'Camiseta Básica Logo Relieve'),
  ('008R', 'Short Deportivo Logo Relieve Crema'),
  ('009R', 'Camiseta Corazón Bordado'),
  ('010R', 'Short Felpa Parche Negro'),
  ('011R', 'Short Deportivo Parche Rojo Negro'),
  ('012R', 'Short Técnico Negro'),
  ('013R', 'Camiseta Cruz Gótica Negro'),
  ('014R', 'Camiseta Bandera Blanco'),
  ('015R', 'Camiseta Letras Góticas Negro'),
  ('016R', 'Camiseta Cruces Azules Blanco'),
  ('017R', 'Camiseta Herradura Negro'),
  ('018R', 'Camiseta Cruces Multicolor Negro'),
  ('019R', 'Hoodie Logo Bordado Negro'),
  ('020R', 'Polo Piqué Cuello Contraste'),
  ('021R', 'Camiseta Oversized Estampado Negro'),
  ('022R', 'Hoodie Corazones Negro'),
  ('023R', 'Camiseta Oversized Logo Negro'),
  ('024R', 'Camiseta Washed Logo Azul'),
  ('025R', 'Camisa Resort Firma'),
  ('026R', 'Camiseta Leopardo Negro/Blanco'),
  ('027R', 'Camisa Resort Palmeras'),
  ('028R', 'Camisa Resort Estampado Azul'),
  ('029R', 'Camiseta Oversized Gráfica Blanco'),
  ('031R', 'Camiseta Rayos X Negro'),
  ('032R', 'Camiseta Logo Garras Naranja'),
  ('034R', 'Camiseta Zepelines Blanco'),
  ('035R', 'Camiseta Mariposas Negro/Blanco'),
  ('036R', 'Camiseta Abejas Amarillo'),
  ('037R', 'Camiseta Graffiti Negro/Blanco'),
  ('038R', 'Camiseta Logo Clásico Colores'),
  ('039R', 'Camiseta Serpiente Negro/Blanco'),
  ('040R', 'Short Deportivo Logo Negro/Blanco'),
  ('041R', 'Camiseta Oversized Logo Tape'),
  ('042R', 'Camiseta Logo Espalda Negro'),
  ('043R', 'Camiseta Logos Múltiples'),
  ('044R', 'Camiseta Camuflaje Negro/Rosa'),
  ('045R', 'Camiseta Gráfica Deportiva Blanco'),
  ('047R', 'Camiseta Avión Blanco'),
  ('048R', 'Camiseta Flores Blanco'),
  ('051R', 'Conjunto Resort Olas Turquesa'),
  ('052R', 'Conjunto Resort Corazones Degradado'),
  ('053R', 'Conjunto Resort Crema'),
  ('054R', 'Conjunto Resort Olas Verde'),
  ('055R', 'Conjunto Tennis Celeste'),
  ('056R', 'Conjunto Resort Conejo Blanco'),
  ('057R', 'Camisa Resort Afiche Blanco'),
  ('058R', 'Camisa Manga Larga Degradado Verde'),
  ('059R', 'Camiseta Hongo Blanco'),
  ('060R', 'Camiseta Cancha Tenis Blanco/Negro'),
  ('061R', 'Jeans Parches Cruces Azul Claro'),
  ('062R', 'Hoodie Cruces Multicolor'),
  ('063R', 'Camiseta Herradura Rosa Negro'),
  ('064R', 'Camiseta Tres Cruces'),
  ('065R', 'Camiseta Herradura Spray'),
  ('066R', 'Camiseta Parches Cruces Cuello'),
  ('067R', 'Short de Baño Negro'),
  ('069R', 'Camiseta Flechas Rojo Blanco'),
  ('070R', 'Camiseta Arte Clásico Negro/Blanco'),
  ('071R', 'Camiseta Flechas Verde'),
  ('072R', 'Short Felpa Flechas Graffiti'),
  ('073R', 'Camiseta Washed Arte Clásico Negro'),
  ('074R', 'Camiseta Corazón Rojo Blanco'),
  ('075R', 'Camiseta Oversized Pintura'),
  ('RR001', 'Camiseta Mangas Cuadros Negro'),
  ('AA001', 'Camiseta Oversized Gráfica Negro'),
  ('AA002', 'Camiseta Oversized Print Blanco'),
  ('AA003', 'Camiseta Oversized Chaleco Blanco'),
  ('AA004', 'Camiseta Oversized Chaleco Rosa Negro'),
  ('AA005', 'Hoodie Zip Retratos Gris'),
  ('AA006', 'Short Felpa Retratos Gris'),
  ('AA007', 'Short Felpa Retratos Negro'),
  ('AA008', 'Camiseta Oversized Retrato Blanco'),
  ('AA009', 'Camiseta Oversized Retrato Negro'),
  ('AA010', 'Camiseta Oversized Fotográfica Negro'),
  ('AA011', 'Camiseta Oversized Mugshot Negro'),
  ('AA012', 'Camiseta Oversized Cine Negro'),
  ('AA013', 'Camiseta Oversized Gráfica Azul/Negro'),
  ('BP001', 'Camiseta Camuflaje Logo Negro'),
  ('BP002', 'Hoodie Full Zip Camuflaje Glow'),
  ('CHR001', 'Camiseta Raglan Manga Larga Cruces Rosa'),
  ('CHR002', 'Camiseta Manga Larga Letras Góticas Negro'),
  ('GD001', 'Camiseta Paint Splatter Blanco'),
  ('GD002', 'Camiseta Paint Splatter Negro'),
  ('GD003', 'Camiseta Logo Vintage Negro'),
  ('CRH003', 'Camiseta Cruces Bordadas Negro'),
  ('CRH004', 'Camiseta Parche Cruz Negro'),
  ('CRH005', 'Camiseta Bolsillo Logo Negro'),
  ('PRL001', 'Camiseta Punto Trenzado Negro'),
  ('CDG001', 'Camiseta Manga Larga Corazón Negro/Blanco'),
  ('ACS001', 'Camiseta Logo Print Negro'),
  ('ACS002', 'Camiseta Bolsillo Negro'),
  ('ACS003', 'Camiseta Washed Azul'),
  ('ACS004', 'Camiseta Manga Larga Logo Negro/Blanco'),
  ('B001', 'Camiseta Racing Team Negro'),
  ('STC001', 'Camiseta Firma Negro'),
  ('STC002', 'Suéter Punto Firma Negro'),
  ('AYO001', 'Sudadera Quarter Zip Azul Marino'),
  ('AYO002', 'Sudadera Quarter Zip Negro'),
  ('ALLS002', 'Camiseta Básica Negro'),
  ('PMS001', 'Camiseta Cocodrilo Negro'),
  ('PMS002', 'Camiseta Osito Negro'),
  ('PMS003', 'Camiseta Logo Spray Blanco'),
  ('CRH006', 'Hoodie Herradura Negro/Blanco'),
  ('CRH007', 'Camiseta Raglan Manga Larga Herradura'),
  ('SUPHOD001', 'Hoodie Logo Vertical Negro'),
  ('CRH008', 'Camiseta Manga Larga Cruces Rosa Negro'),
  ('CRH009', 'Camiseta Manga Larga Estampado Azul Blanco'),
  ('CRH010', 'Camiseta Manga Larga Cruces Multicolor Negro'),
  ('CRH011', 'Camiseta Manga Larga Herradura Negro/Blanco'),
  ('CRH012', 'Camiseta Manga Larga Herradura Blanco'),
  ('CRH013', 'Camiseta Raglan Manga Larga Azul/Blanco'),
  ('CRH014', 'Camiseta Raglan Manga Larga Negro/Blanco');

create table if not exists public.respaldo_nombres_20260924 (
  tabla text not null,
  fila_id uuid not null,
  nombre_anterior text not null,
  created_at timestamptz not null default now(),
  primary key (tabla, fila_id)
);
alter table public.respaldo_nombres_20260924 enable row level security;

insert into public.respaldo_nombres_20260924 (tabla, fila_id, nombre_anterior)
select 'productos', p.id, p.nombre from public.productos p
join nombres_nuevos n on n.codigo = upper(trim(p.codigo)) where p.nombre is distinct from n.nombre
on conflict do nothing;
insert into public.respaldo_nombres_20260924 (tabla, fila_id, nombre_anterior)
select 'pedido_items', i.id, i.producto from public.pedido_items i
join nombres_nuevos n on n.codigo = upper(trim(i.codigo_producto)) where i.producto is distinct from n.nombre
on conflict do nothing;
insert into public.respaldo_nombres_20260924 (tabla, fila_id, nombre_anterior)
select 'solicitudes', s.id, s.producto from public.solicitudes s
join nombres_nuevos n on n.codigo = upper(trim(s.producto_codigo)) where s.producto is distinct from n.nombre
on conflict do nothing;

update public.productos p set nombre = n.nombre
from nombres_nuevos n where n.codigo = upper(trim(p.codigo)) and p.nombre is distinct from n.nombre;

update public.pedido_items i set producto = n.nombre
from nombres_nuevos n where n.codigo = upper(trim(i.codigo_producto)) and i.producto is distinct from n.nombre;

update public.solicitudes s set producto = n.nombre
from nombres_nuevos n where n.codigo = upper(trim(s.producto_codigo)) and s.producto is distinct from n.nombre;

commit;

-- Para revertir:
-- update public.productos t set nombre = r.nombre_anterior from public.respaldo_nombres_20260924 r where r.tabla='productos' and r.fila_id=t.id;
-- update public.pedido_items t set producto = r.nombre_anterior from public.respaldo_nombres_20260924 r where r.tabla='pedido_items' and r.fila_id=t.id;
-- update public.solicitudes t set producto = r.nombre_anterior from public.respaldo_nombres_20260924 r where r.tabla='solicitudes' and r.fila_id=t.id;
